server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: core-service
#          uri: http://core-service:8189
          uri: http://localhost:8189
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: cart-service
#          uri: http://cart-service:8190
          uri: http://localhost:8190
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-cart
            - JwtAuthFilter
        - id: auth-service
#          uri: http://auth-service:8187
          uri: http://localhost:8187
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
        - id: favorite-service
#          uri: http://favorite-service:8192
          uri: http://localhost:8192
          predicates:
            - Path=/favorite/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-favorite
            - JwtAuthFilter
        - id: comment-service
#          uri: http://comment-service:8195
          uri: http://localhost:8195
          predicates:
            - Path=/comment/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-comment
            - JwtAuthFilter
        - id: email-service
#          uri: http://email-service:8193
          uri: http://localhost:8193
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-email
            - JwtAuthFilter
        - id: image-service
#          uri: http://image-service:8194
          uri: http://localhost:8194
          predicates:
            - Path=/image/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-image
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
