server:
  port: 8192
  servlet:
    context-path: /market-favorite
integrations:
  product-service:
    url: http://core-service:8189/market-core/
#    url: http://localhost:8189/market-core/
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000