server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:market-core;MODE=PostgreSQL
#    username: sa
#    password:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
integrations:
  cart-service:
#    url: http://cart-service:8190/market-cart/
    url: http://localhost:8190/market-cart/
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000